# Generated by Django 4.2.14 on 2025-10-29 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_id", models.IntegerField(default=0)),
                (
                    "willingness_to_pay",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(22),
                        ]
                    ),
                ),
                ("preference", models.CharField(max_length=1)),
                (
                    "out_door_pf",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "in_door_pf",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_id", models.IntegerField(default=0)),
                (
                    "willingness_to_pay",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                ("preference", models.CharField(max_length=1)),
                (
                    "travel_cost_to_A",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-9),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
                (
                    "travel_cost_to_B",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-9),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
            ],
        ),
    ]
