# Generated by Django 4.2.14 on 2025-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_id", models.IntegerField()),
                ("willingness_to_pay", models.FloatField()),
                ("preference", models.CharField(max_length=1)),
            ],
        ),
    ]
