# Generated by Django 4.2.14 on 2025-07-06 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulationGame", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_id", models.IntegerField()),
                ("willingness_to_pay", models.FloatField()),
                ("preference", models.CharField(max_length=1)),
                (
                    "out_door_pf",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
            ],
        ),
    ]
