# Generated by Django 4.2.14 on 2025-10-29 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulationGame", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="willingness_to_pay",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(24),
                ]
            ),
        ),
    ]
