# Generated by Django 4.2.14 on 2025-07-07 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulationGame", "0003_buyer_in_door_pf_alter_buyer_out_door_pf"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="travel_cost_to_A",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="travel_cost_to_B",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
