# Generated by Django 4.2.14 on 2025-10-06 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulationGame", "0004_supplier_travel_cost_to_a_supplier_travel_cost_to_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="in_door_pf",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="out_door_pf",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="travel_cost_to_A",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="travel_cost_to_B",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
