# Generated by Django 4.2.14 on 2025-10-12 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulationGame",
            "0005_alter_buyer_in_door_pf_alter_buyer_out_door_pf_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="in_door_pf",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(13),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="out_door_pf",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(13),
                ]
            ),
        ),
    ]
