# Generated by Django 4.2.14 on 2025-10-12 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulationGame", "0006_alter_buyer_in_door_pf_alter_buyer_out_door_pf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="willingness_to_pay",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(15),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="travel_cost_to_A",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="travel_cost_to_B",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="willingness_to_pay",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(30),
                ]
            ),
        ),
    ]
